# -*- coding: utf-8 -*-
"""reto 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sSFoDm9KSimmKIEGFXRjKhejQCHmRGH9
"""

luke = int(input('meses de experiencia de luke: '))
han = 2 * luke + 4
leia = (han + luke) // 5
print("%d %d %d" % (leia,luke,han))

if han <= 20:
    print ('junior')
elif 21 <= han <= 30:
    print ('semi-senior')
elif 31 <= han <= 50:
    print ('senior')
elif han >= 50:
    print ('master')

